name: ameiva
description: A lib graphic 2d html5.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  html: ^0.14.0+3

dev_dependencies:
  build_runner: ^1.6.0
  build_test: any
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.9.4
